### ISSUE TITLE
Allow proper multithreading.... I cannot run ffmpeg 80times lol bro 

### ISSUE THREAD

**Issue by orithecapper** [g-fb/kagura#1]
![image](https://github.com/g-fb/kagura/assets/131520229/a4ae7e52-9f1b-4e3c-9fe7-7ed2f848b3aa)

**Comment by orithecapper** [comment]
https://dl.seyarabata.com:9006/seyarabata/136/4d6/49f/52f/lmao.mp3

**Comment by g-fb** [comment]
Feel free to implement proper multithreading yourself... lol bro.

**Comment by orithecapper** [comment]
> Feel free to implement proper multithreading yourself... lol bro.

I ended up using, 
https://github.com/amietn/vcsi/tree/master/vcsi

and you should too, soyboy zoomer
